services:
  api:
    image: ${APP_NAME}-${ENVIRONMENT}
    hostname: ${APP_NAME}-${ENVIRONMENT}
    build:
      context: .
      dockerfile: .docker/Dockerfile.${DOCKER_SUFFIX}
    restart: always
    env_file:
      - .env
    networks:
      microservices:
        aliases:
          - ${APP_NAME}-${ENVIRONMENT}
    ports:
      - ${EXTERNAL_PORT}:${API_PORT}
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules

  test:
    image: ${APP_NAME}-${ENVIRONMENT}-test
    hostname: ${APP_NAME}-${ENVIRONMENT}-test
    build:
      context: .
      dockerfile: .docker/Dockerfile.${DOCKER_SUFFIX}
    env_file:
      - .env
    networks:
      microservices:
        aliases:
          - ${APP_NAME}-${ENVIRONMENT}-test
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run test

networks:
  microservices:
    external: true
    name: microservices_network
